name: Check version change and Run tests

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install all dependencies
        run: npm install

      - name: Run tests
        run: npm test

  check-version:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # this is required to fetch the previous commit

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install production dependencies only
        run: npm ci --only=prod

      - name: Check version change
        run: |
          # Get the version in the current commit
          current_version=$(node -p "require('./package.json').version")

          # Checkout the master branch
          git fetch origin master
          git checkout master

          # Get the version in the master branch
          master_version=$(node -p "require('./package.json').version")

          # Check if the versions are different
          if [[ "$current_version" == "$master_version" ]]; then
            echo "Version has not changed from master!"
            exit 1
          else
            echo "Version has changed from $master_version in master to $current_version."
          fi
